# Generated by Django 5.2.16 on 2026-07-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('Customer_name', models.CharField(max_length=100)),
                ('modile_no', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
