# Generated by Django 4.2.23 on 2026-07-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='modile_no',
            new_name='mobile_no',
        ),
    ]
