# Generated by Django 4.2.23 on 2026-07-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('milk_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('milk_type', models.CharField(choices=[('Cow', 'Cow'), ('Buffalo', 'Buffalo')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
